In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/jpx-tokyo-stock-exchange-prediction/stock_list.csv
/kaggle/input/jpx-tokyo-stock-exchange-prediction/example_test_files/sample_submission.csv
/kaggle/input/jpx-tokyo-stock-exchange-prediction/example_test_files/options.csv
/kaggle/input/jpx-tokyo-stock-exchange-prediction/example_test_files/financials.csv
/kaggle/input/jpx-tokyo-stock-exchange-prediction/example_test_files/secondary_stock_prices.csv
/kaggle/input/jpx-tokyo-stock-exchange-prediction/example_test_files/trades.csv
/kaggle/input/jpx-tokyo-stock-exchange-prediction/example_test_files/stock_prices.csv
/kaggle/input/jpx-tokyo-stock-exchange-prediction/jpx_tokyo_market_prediction/competition.cpython-37m-x86_64-linux-gnu.so
/kaggle/input/jpx-tokyo-stock-exchange-prediction/jpx_tokyo_market_prediction/__init__.py
/kaggle/input/jpx-tokyo-stock-exchange-prediction/data_specifications/stock_fin_spec.csv
/kaggle/input/jpx-tokyo-stock-exchange-prediction/data_specifications/trades_spec.csv
/kaggle/input/jpx-tokyo-stock-

In [3]:
df = pd.read_csv("../input/jpx-tokyo-stock-exchange-prediction/train_files/stock_prices.csv")
df

RowId        Date  SecuritiesCode    Open    High     Low  \
0        20170104_1301  2017-01-04            1301  2734.0  2755.0  2730.0   
1        20170104_1332  2017-01-04            1332   568.0   576.0   563.0   
2        20170104_1333  2017-01-04            1333  3150.0  3210.0  3140.0   
3        20170104_1376  2017-01-04            1376  1510.0  1550.0  1510.0   
4        20170104_1377  2017-01-04            1377  3270.0  3350.0  3270.0   
...                ...         ...             ...     ...     ...     ...   
2332526  20211203_9990  2021-12-03            9990   514.0   528.0   513.0   
2332527  20211203_9991  2021-12-03            9991   782.0   794.0   782.0   
2332528  20211203_9993  2021-12-03            9993  1690.0  1690.0  1645.0   
2332529  20211203_9994  2021-12-03            9994  2388.0  2396.0  2380.0   
2332530  20211203_9997  2021-12-03            9997   690.0   711.0   686.0   

          Close   Volume  AdjustmentFactor  ExpectedDividend  SupervisionFlag  \
0        2742.0    31400               1.0               NaN            False   
1         571.0  2798500               1.0               NaN            False   
2        3210.0   270800               1.0               NaN            False   
3        1550.0    11300               1.0               NaN            False   
4        3330.0   150800               1.0               NaN            False   
...         ...      ...               ...               ...              ...   
2332526   528.0    44200               1.0               NaN            False   
2332527   794.0    35900               1.0               NaN            False   
2332528  1645.0     7200               1.0               NaN            False   
2332529  2389.0     6500               1.0               NaN            False   
2332530   696.0   381100               1.0               NaN            False   

           Target  
0        0.000730  
1        0.012324  
2        0.006154  
3        0.011053  
4        0.003026  
...           ...  
2332526  0.034816  
2332527  0.025478  
2332528 -0.004302  
2332529  0.009098  
2332530  0.018414  

[2332531 rows x 12 columns]

RowId        Date  SecuritiesCode    Open    High     Low  \
0        20170104_1301  2017-01-04            1301  2734.0  2755.0  2730.0   
1865     20170105_1301  2017-01-05            1301  2743.0  2747.0  2735.0   
3730     20170106_1301  2017-01-06            1301  2734.0  2744.0  2720.0   
5595     20170110_1301  2017-01-10            1301  2745.0  2754.0  2735.0   
7460     20170111_1301  2017-01-11            1301  2748.0  2752.0  2737.0   
...                ...         ...             ...     ...     ...     ...   
2322531  20211129_1301  2021-11-29            1301  2975.0  2984.0  2951.0   
2324531  20211130_1301  2021-11-30            1301  2953.0  2997.0  2900.0   
2326531  20211201_1301  2021-12-01            1301  2909.0  2936.0  2909.0   
2328531  20211202_1301  2021-12-02            1301  2949.0  2973.0  2933.0   
2330531  20211203_1301  2021-12-03            1301  2983.0  2983.0  2965.0   

          Close  Volume  AdjustmentFactor  ExpectedDividend  SupervisionFlag  \
0        2742.0   31400               1.0               NaN            False   
1865     2738.0   17900               1.0               NaN            False   
3730     2740.0   19900               1.0               NaN            False   
5595     2748.0   24200               1.0               NaN            False   
7460     2745.0    9300               1.0               NaN            False   
...         ...     ...               ...               ...              ...   
2322531  2951.0   14300               1.0               NaN            False   
2324531  2900.0   20500               1.0               NaN            False   
2326531  2911.0   10600               1.0               NaN            False   
2328531  2933.0   15200               1.0               NaN            False   
2330531  2982.0   11400               1.0               NaN            False   

           Target  
0        0.000730  
1865     0.002920  
3730    -0.001092  
5595    -0.005100  
7460    -0.003295  
...           ...  
2322531  0.003793  
2324531  0.007558  
2326531  0.016706  
2328531 -0.003689  
2330531  0.031639  

[1202 rows x 12 columns]

In [ ]:
for col in df.columns:
    print(col, len(df[df[col].isnull()]))

In [ ]:
len(df[df['SupervisionFlag']==True])/len(df[df['SupervisionFlag']==False])

In [55]:
#'ExpectedDividend' could be per security, need to check before dropping this.
codes = pd.unique(df['SecuritiesCode'])
for code in codes: 
    filtered = df[df['SecuritiesCode']==code]
    if not len(filtered[filtered['Close'].isnull()]):
        break
        
print(code)
    

7354


# Try simple regression on this data - RT

In [60]:
df_sample = df[df['SecuritiesCode'] == code].sort_values('Date',axis=0)
df_train = df_sample.iloc[0:int(0.8*len(df_sample))]
df_test = df_sample.iloc[int(0.8*len(df_sample)):]

In [61]:
len(df_train)

229

In [71]:
window = 5
x_train = []
y_train = []
for i in range(0,len(df_train)-window-1):
    indices = list(range(i,i+window))
    x_train.append(df_train['Close'].iloc[indices].to_numpy())
    y_train.append(df_train['Target'].iloc[i+window])
x_train = np.array(x_train)
y_train = np.array(y_train)
    
print(x_train,y_train)
    
    

[[2532. 2733. 2672. 2666. 2598.]
 [2733. 2672. 2666. 2598. 2565.]
 [2672. 2666. 2598. 2565. 2613.]
 ...
 [4015. 4190. 4070. 4020. 4090.]
 [4190. 4070. 4020. 4090. 4260.]
 [4070. 4020. 4090. 4260. 4370.]] [ 0.03176426 -0.03523739 -0.03344867  0.00676213  0.02015014 -0.00116189
 -0.02597906 -0.03025478  0.0045156  -0.00653862  0.01604278  0.03238866
 -0.02666667  0.01168413 -0.02708084  0.00941465  0.013382   -0.03081232
  0.02683732  0.017692    0.02647175  0.01770593 -0.03025719  0.00156006
 -0.01479751 -0.00474308  0.0166799   0.05585938  0.02108768  0.
 -0.00036232 -0.00688655  0.00109489  0.00401021 -0.00580973  0.06099343
 -0.04165232 -0.00610632  0.04011565 -0.00521195 -0.00034928 -0.03284416
  0.0191474  -0.01240695 -0.03804738  0.01902985 -0.0270963  -0.03086187
  0.00737864 -0.0073246  -0.00582524 -0.009375    0.00867508  0.02541048
  0.00038124  0.02362805  0.00707372 -0.0232902   0.02649508  0.0129056
  0.00910084  0.01443001  0.02098151  0.0163706   0.00753941  0.05442177
  

In [72]:
from sklearn.linear_model import LinearRegression as LR
from sklearn.ensemble import RandomForestRegressor as RFR
from sklearn.metrics import r2_score
# reg = LR()
reg=RFR()
reg.fit(x_train,y_train)
print(reg.score(x_train,y_train))

0.8460041877369255
